### ISSUE TITLE
OR in expressions

### ISSUE THREAD

**Issue by maximelefrancois86** [blake-regalia/linked-data.syntaxes#11]
currently after `||` the parser expects two `valueLogical` 

```
SELECT * {
  FILTER ( true && true || true || true ) 
}
```

need to change line 1434 to `set: conditionalOrExpression` to solve issue

**Comment by blake-regalia** [comment]
Fixed in [v0.5.0](https://github.com/blake-regalia/linked-data.syntaxes/releases/tag/v0.5.0)
