### ISSUE TITLE
Export (copy/paste) SPARQL with colors outside of ST ?

### ISSUE THREAD

**Issue by tfrancart** [blake-regalia/linked-data.syntaxes#17]
Hi

I'd like to copy/paste a higlighted SPARQL query from ST to Powerpoint.
I have tried SublimeHighlight and ExportHTML plugin, but I can't manage to have the same color highlighting when pasting in Powerpoint as I have in ST.

Do you know if LinkedData package can work in conjunction with these export plugins ?
Could you indicate a quick procedure to copy/paste the highlighted query from ST to Powerpoint ?

Many thanks again for this useful package

**Comment by tfrancart** [comment]
To give you an idea, here is what I get when exporting using ExportHTML plugin : note the color differences between ST and what I see in the browser :

![Capture](https://user-images.githubusercontent.com/2728945/71579046-05c25080-2afb-11ea-91d4-13db7753cccf.PNG)

**Comment by blake-regalia** [comment]
Thanks for the issue -- I am curious about this as well. Have you looked into the [`color_scheme` setting for the ExportHTML plugin](https://facelessuser.github.io/ExportHtml/usage/)?

**Comment by blake-regalia** [comment]
@tfrancart I opened [an issue in ExportHtml](https://github.com/facelessuser/ExportHtml/issues/67) which addresses the problem. Will keep this opened until that is resolved.

**Comment by tfrancart** [comment]
Thanks !

**Comment by blake-regalia** [comment]
The ExportHtml plugin now supports HSL blending but unfortunately the algorithm that was implemented in the patch is not producing the same colors as ST3, so the macaron-dark and macaron-light color schemes come out looking very desaturated. Will try to find the bug, which must lie [somewhere here](https://github.com/facelessuser/ExportHtml/commit/f7bd0069d59225ba4d455d1943e5d75e4fb9cfd0#diff-6583d786363c83aa4958c59ebc23f832) in case you'd like to help out. A reference implementation [can be found here](https://github.com/jonathantneal/postcss-color-mod-function/blob/master/lib/color.js#L166).

**Comment by blake-regalia** [comment]
Following along at https://github.com/sublimehq/sublime_text/issues/3176
