### ISSUE TITLE
Any plan to port this extension to SublimeText 4 ?

### ISSUE THREAD

**Issue by tfrancart** [blake-regalia/linked-data.syntaxes#31]
Thanks again for this very helpful extension.
Any plan to port it to ST 4 ? ST3 is now like... old.

**Comment by blake-regalia** [comment]
It is available in ST4 (has been for years now :) ). Are you having trouble finding or installing it from PackageControl?

https://github.com/blake-regalia/linked-data.syntaxes/blob/d8ba9f81c6233cf5f041ba4561b8c0576bbdba37/channels/sublime/package-control.json#L26-L31

**Comment by tfrancart** [comment]
Ho, my bad - yes I can install it on ST4. Just probably the README should be updated, it got me confused:

![image](https://github.com/blake-regalia/linked-data.syntaxes/assets/2728945/e262618f-e2ad-4e18-938c-2b749edc74bf)
