### ISSUE TITLE
SPARQL INSERT GRAPH not correctly highlighted ?

### ISSUE THREAD

**Issue by tfrancart** [blake-regalia/linked-data.syntaxes#4]
Below is a valid SPARQL query using `INSERT { GRAPH { ... } }` syntax for which I think the highlignting is not correct.

![sparql-insert-graph](https://user-images.githubusercontent.com/2728945/57864899-f658f600-77fc-11e9-92b1-1f7722295fe2.png)

**Comment by blake-regalia** [comment]
Thanks for the report. Fixed in v0.4.22
